[project]
name = "namaste"
version = "0.1.0"
description = ""
authors = [
    {name = "Ekaterina Golovina",email = "ekaterinagolovina0771@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django (>=5.2.6,<6.0.0)",
    "python-dotenv (>=1.1.1,<2.0.0)",
    "django-debug-toolbar (>=6.0.0,<7.0.0)",
    "pillow (>=11.3.0,<12.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
