# Generated by Django 5.2.6 on 2025-09-13 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_review_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='practice',
        ),
    ]
