# Generated by Django 5.2.6 on 2025-09-13 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_application_practice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='image',
            new_name='photo',
        ),
    ]
