# Generated by Django 5.2.6 on 2025-09-13 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_image_coach_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время записи'),
        ),
        migrations.AlterField(
            model_name='review',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='core.coach', verbose_name='Тренер'),
        ),
    ]
