# Generated by Django 5.2.6 on 2025-09-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_application_appointment_time_alter_review_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(blank=True, max_length=50, null=True, verbose_name='Дни')),
                ('times', models.CharField(blank=True, max_length=50, null=True, verbose_name='Время')),
            ],
        ),
    ]
