# Generated by Django 5.2.6 on 2025-09-13 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_schedule_options_remove_schedule_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
    ]
