# Generated by Django 5.2.6 on 2025-09-13 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_time_schedule_start_time_schedule_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='name',
        ),
    ]
