# Generated by Django 5.2.6 on 2025-09-13 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_schedule_day_of_week_remove_schedule_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='end_time',
        ),
    ]
