# Generated by Django 5.2.6 on 2025-09-14 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_schedule_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='appointment_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='application',
            name='appointment_time',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Время записи'),
        ),
    ]
