# Generated by Django 5.2.6 on 2025-09-14 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_application_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schedule'),
        ),
    ]
