# Generated by Django 5.2.6 on 2025-09-14 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_application_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='application',
            name='appointment_time',
        ),
    ]
