# Generated by Django 5.2.6 on 2025-09-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_application_appointment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='location',
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('confirmed', 'Подтвержденная'), ('completed', 'Завершеная'), ('canceled', 'Отмененая'), ('reserve', 'Резерв')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
