# Generated by Django 5.2.6 on 2025-09-14 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_schedule_location_alter_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='coach',
        ),
        migrations.DeleteModel(
            name='Practice',
        ),
        migrations.DeleteModel(
            name='Coach',
        ),
    ]
