# Generated by Django 5.2.6 on 2025-09-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_review_coach_delete_practice_delete_coach'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Расписание'},
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('confirmed', 'Подтвержденная'), ('completed', 'Завершенная'), ('canceled', 'Отмененная'), ('reserve', 'Резерв')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
