# Generated by Django 5.2.6 on 2025-09-15 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_schedule_options_alter_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='photo',
        ),
    ]
