# Generated by Django 5.2.6 on 2025-09-16 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_review_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Практика', 'verbose_name_plural': 'Практики'},
        ),
        migrations.AddField(
            model_name='schedule',
            name='duration',
            field=models.PositiveIntegerField(default=90, help_text='Длительность практики в минутах', verbose_name='Длительность'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.RemoveField(
            model_name='application',
            name='schedule',
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='coaches', verbose_name='Фото')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('experience', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Опыт работы')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Активен')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('schedules', models.ManyToManyField(default=None, related_name='coaches', to='core.schedule', verbose_name='Практики')),
            ],
            options={
                'verbose_name': 'Инструктор',
                'verbose_name_plural': 'Инструкторы',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.coach', verbose_name='Инструктор'),
        ),
        migrations.AddField(
            model_name='application',
            name='schedule',
            field=models.ManyToManyField(default=None, related_name='applications', to='core.schedule', verbose_name='Практики'),
        ),
    ]
