# Generated by Django 5.2.6 on 2025-09-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_schedule_options_schedule_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
