# Generated by Django 5.2.6 on 2025-09-19 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_coach_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.RenameField(
            model_name='application',
            old_name='schedule',
            new_name='schedules',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='description',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='price',
        ),
        migrations.AddField(
            model_name='application',
            name='appointment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата практики'),
        ),
        migrations.AddField(
            model_name='review',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='core.coach', verbose_name='Инструктор'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coach',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
