# Generated by Django 5.2.6 on 2025-09-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_schedule_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='schedules',
            field=models.ManyToManyField(blank=True, default=None, related_name='coaches', to='core.schedule', verbose_name='Практики'),
        ),
    ]
