# Generated by Django 5.2.6 on 2025-09-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_coach_schedules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='coach',
        ),
        migrations.AlterField(
            model_name='coach',
            name='schedules',
            field=models.ManyToManyField(default=None, related_name='coaches', to='core.schedule', verbose_name='Практики'),
        ),
    ]
