# Generated by Django 5.2.6 on 2025-09-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_schedule_coach_alter_coach_schedules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='appointment_date',
        ),
        migrations.AddField(
            model_name='application',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
