# Generated by Django 5.2.6 on 2025-09-19 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_application_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
