# Generated by Django 5.2.6 on 2025-09-20 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_review_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.coach', verbose_name='Инструктор'),
        ),
    ]
