# Generated by Django 5.2.6 on 2025-09-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_schedule_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='schedules',
            field=models.ManyToManyField(blank=True, default=None, related_name='applications', to='core.schedule', verbose_name='Практики'),
        ),
    ]
